/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMS;

import Entyty.part;
import Entyty.product;
import com.sun.org.apache.xml.internal.security.algorithms.implementations.IntegrityHmac;
import componentANDtools.Tools;
import componentANDtools.textfeild;
import db.go;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdelmoneam Ismael
 */
public class daily extends javax.swing.JFrame {

    /**
     * Creates new form sell
     */
    public daily() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        SELLPAnnel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        RIDD = new javax.swing.JRadioButton();
        RDD = new javax.swing.JRadioButton();
        RKK = new javax.swing.JRadioButton();
        RCC = new javax.swing.JRadioButton();
        RPP = new javax.swing.JRadioButton();
        RNN = new javax.swing.JRadioButton();
        SK = new textfeild(15);
        jScrollPane8 = new javax.swing.JScrollPane();
        TBB = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tBforsell = new javax.swing.JTable();
        bottonblue3 = new componentANDtools.bottonblue();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        num1 = new componentANDtools.textfeild(10);
        bottonRamady11 = new componentANDtools.bottonRamady1();
        bottongreen1 = new componentANDtools.bottongreen();
        jScrollPane10 = new javax.swing.JScrollPane();
        TT = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        sellnum = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        SaleForPerson = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        PERsonPArt = new javax.swing.JTable();
        RPNUM = new javax.swing.JRadioButton();
        RPNAMe = new javax.swing.JRadioButton();
        jTextField1 = new componentANDtools.textfeild(15);
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        IDPART = new javax.swing.JLabel();
        bottonblue2 = new componentANDtools.bottonblue();
        ADDPRODUCT = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        RID = new javax.swing.JRadioButton();
        RN = new javax.swing.JRadioButton();
        RP = new javax.swing.JRadioButton();
        RC = new javax.swing.JRadioButton();
        RK = new javax.swing.JRadioButton();
        searchkey = new textfeild(15);
        jScrollPane6 = new javax.swing.JScrollPane();
        TB = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        RD = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        num = new componentANDtools.textfeild(10);
        jLabel22 = new javax.swing.JLabel();
        bottonblue1 = new componentANDtools.bottonblue();
        All_details = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        product_table1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        customer = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        phone = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        select_1 = new javax.swing.JPanel();
        select_2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        select_3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        select_4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        select_5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SELLPAnnel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 27)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 255));
        jLabel26.setText("Now you are going to sale ...");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setText("Search by :-");

        RIDD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RIDD.setText("ID");
        RIDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RIDDActionPerformed(evt);
            }
        });

        RDD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RDD.setText("Discribe");

        RKK.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RKK.setText("Kind");

        RCC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RCC.setText("comment");

        RPP.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RPP.setText("price");

        RNN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RNN.setText("number");

        SK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SKKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SKKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SKKeyTyped(evt);
            }
        });

        TBB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "النوع", "الوصف", "العدد", "السعر"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBBMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(TBB);

        tBforsell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "النوع", "الوصف", "العدد", "السعر", "تعليق", "السعر الاصلي"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tBforsell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBforsellMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tBforsell);
        if (tBforsell.getColumnModel().getColumnCount() > 0) {
            tBforsell.getColumnModel().getColumn(0).setMaxWidth(50);
            tBforsell.getColumnModel().getColumn(1).setMaxWidth(100);
            tBforsell.getColumnModel().getColumn(3).setMaxWidth(40);
            tBforsell.getColumnModel().getColumn(4).setMaxWidth(40);
            tBforsell.getColumnModel().getColumn(6).setMaxWidth(80);
        }

        bottonblue3.setText("Add to sell table");
        bottonblue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonblue3ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setText("Number :-");

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setText("ID_Product :-");

        bottonRamady11.setText("another one");
        bottonRamady11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonRamady11ActionPerformed(evt);
            }
        });

        bottongreen1.setText("نفذ عملية البيع");
        bottongreen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottongreen1ActionPerformed(evt);
            }
        });

        TT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "num"
            }
        ));
        jScrollPane10.setViewportView(TT);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setText("السعر النهائي");

        sellnum.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        sellnum.setText("0");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("جنية");

        javax.swing.GroupLayout SELLPAnnelLayout = new javax.swing.GroupLayout(SELLPAnnel);
        SELLPAnnel.setLayout(SELLPAnnelLayout);
        SELLPAnnelLayout.setHorizontalGroup(
            SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SELLPAnnelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SELLPAnnelLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RIDD)
                        .addGap(18, 18, 18)
                        .addComponent(RDD)
                        .addGap(27, 27, 27)
                        .addComponent(RKK)
                        .addGap(18, 18, 18)
                        .addComponent(RCC)
                        .addGap(18, 18, 18)
                        .addComponent(RPP)
                        .addGap(18, 18, 18)
                        .addComponent(RNN))
                    .addGroup(SELLPAnnelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(SK, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SELLPAnnelLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SELLPAnnelLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELLPAnnelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(SELLPAnnelLayout.createSequentialGroup()
                                        .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELLPAnnelLayout.createSequentialGroup()
                                                .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel30)
                                                    .addComponent(jLabel29))
                                                .addGap(27, 27, 27))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELLPAnnelLayout.createSequentialGroup()
                                                .addComponent(bottonRamady11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                        .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bottonblue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(SELLPAnnelLayout.createSequentialGroup()
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELLPAnnelLayout.createSequentialGroup()
                                                .addComponent(sellnum, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                                .addGap(15, 15, 15)
                                                .addComponent(jLabel31))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SELLPAnnelLayout.createSequentialGroup()
                                                .addComponent(bottongreen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(63, 63, 63)))))
                                .addGap(23, 23, 23))))))
            .addGroup(SELLPAnnelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SELLPAnnelLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(311, Short.MAX_VALUE)))
        );
        SELLPAnnelLayout.setVerticalGroup(
            SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SELLPAnnelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(RIDD)
                    .addComponent(RDD)
                    .addComponent(RKK)
                    .addComponent(RCC)
                    .addComponent(RPP)
                    .addComponent(RNN))
                .addGap(18, 18, 18)
                .addComponent(SK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(SELLPAnnelLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottonblue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottonRamady11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(bottongreen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellnum, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(SELLPAnnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SELLPAnnelLayout.createSequentialGroup()
                    .addGap(217, 217, 217)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(278, Short.MAX_VALUE)))
        );

        jPanel1.add(SELLPAnnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 950, 660));

        SaleForPerson.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(0, 0, 102));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Now We Are Sale part to PERSON .......");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PERsonPArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم القسط", "IDperson", "الاسم", "سعر القسط", "وقت الانتهاء", "المتبقي", "سعر اخر قسط", "المدة كاملة"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PERsonPArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PERsonPArtMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(PERsonPArt);
        if (PERsonPArt.getColumnModel().getColumnCount() > 0) {
            PERsonPArt.getColumnModel().getColumn(2).setMinWidth(200);
            PERsonPArt.getColumnModel().getColumn(2).setMaxWidth(250);
        }

        RPNUM.setText("Number of part");

        RPNAMe.setText("Name of Customer");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setText("Search by :-");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("The Real Price wich   ");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("The Real Price wich   ");

        IDPART.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        bottonblue2.setText("GIVED");
        bottonblue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonblue2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SaleForPersonLayout = new javax.swing.GroupLayout(SaleForPerson);
        SaleForPerson.setLayout(SaleForPersonLayout);
        SaleForPersonLayout.setHorizontalGroup(
            SaleForPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaleForPersonLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SaleForPersonLayout.createSequentialGroup()
                .addGroup(SaleForPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SaleForPersonLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel24)
                        .addGap(35, 35, 35)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(RPNUM)
                        .addGap(18, 18, 18)
                        .addComponent(RPNAMe))
                    .addGroup(SaleForPersonLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaleForPersonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SaleForPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bottonblue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SaleForPersonLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(36, 36, 36)
                        .addComponent(IDPART)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        SaleForPersonLayout.setVerticalGroup(
            SaleForPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaleForPersonLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(SaleForPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RPNUM)
                    .addComponent(RPNAMe)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SaleForPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SaleForPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IDPART, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(bottonblue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        jPanel1.add(SaleForPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 960, 660));

        ADDPRODUCT.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Now We Are Adding Products .......");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        RID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RID.setText("ID");

        RN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RN.setText("number");

        RP.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RP.setText("price");

        RC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RC.setText("comment");

        RK.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RK.setText("Kind");

        searchkey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchkeyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchkeyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchkeyKeyTyped(evt);
            }
        });

        TB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "النوع", "الوصف", "العدد", "السعر", "تعليق", "السعر الاصلي"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TB);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setText("Search by :-");

        RD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RD.setText("Discribe");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("ID_Product :-");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Number :-");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setText("(Note) That this Number Will Add not Update ");

        bottonblue1.setText("Add");
        bottonblue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonblue1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ADDPRODUCTLayout = new javax.swing.GroupLayout(ADDPRODUCT);
        ADDPRODUCT.setLayout(ADDPRODUCTLayout);
        ADDPRODUCTLayout.setHorizontalGroup(
            ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADDPRODUCTLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ADDPRODUCTLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ADDPRODUCTLayout.createSequentialGroup()
                        .addGroup(ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ADDPRODUCTLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RID)
                                .addGap(18, 18, 18)
                                .addComponent(RD)
                                .addGap(27, 27, 27)
                                .addComponent(RK)
                                .addGap(18, 18, 18)
                                .addComponent(RC)
                                .addGap(18, 18, 18)
                                .addComponent(RP)
                                .addGap(18, 18, 18)
                                .addComponent(RN))
                            .addGroup(ADDPRODUCTLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel22)))
                        .addContainerGap())
                    .addGroup(ADDPRODUCTLayout.createSequentialGroup()
                        .addComponent(jScrollPane6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ADDPRODUCTLayout.createSequentialGroup()
                                .addGroup(ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(27, 27, 27)
                                .addGroup(ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ADDPRODUCTLayout.createSequentialGroup()
                                .addComponent(bottonblue1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ADDPRODUCTLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(searchkey, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(574, 574, 574))
        );
        ADDPRODUCTLayout.setVerticalGroup(
            ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADDPRODUCTLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(RID)
                    .addComponent(RD)
                    .addComponent(RK)
                    .addComponent(RC)
                    .addComponent(RP)
                    .addComponent(RN))
                .addGap(22, 22, 22)
                .addComponent(searchkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ADDPRODUCTLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ADDPRODUCTLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(ADDPRODUCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bottonblue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        id.setEnabled(false);

        jPanel1.add(ADDPRODUCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 960, 660));

        All_details.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Now We Are Showing Your Data Details .......");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Incomplete products  :-");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        product_table.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "kind", "discribe", "number", "price", "comment", "السعر الاصلي"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        product_table.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(product_table);
        if (product_table.getColumnModel().getColumnCount() > 0) {
            product_table.getColumnModel().getColumn(0).setMinWidth(30);
            product_table.getColumnModel().getColumn(0).setMaxWidth(39);
            product_table.getColumnModel().getColumn(3).setMinWidth(60);
            product_table.getColumnModel().getColumn(3).setMaxWidth(60);
            product_table.getColumnModel().getColumn(4).setMinWidth(60);
            product_table.getColumnModel().getColumn(4).setMaxWidth(60);
            product_table.getColumnModel().getColumn(6).setMinWidth(60);
            product_table.getColumnModel().getColumn(6).setMaxWidth(60);
        }

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Person have to pay :-");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        product_table1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        product_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "kind", "discribe", "number", "price", "comment", "السعر الاصلي"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(product_table1);
        if (product_table1.getColumnModel().getColumnCount() > 0) {
            product_table1.getColumnModel().getColumn(0).setMinWidth(30);
            product_table1.getColumnModel().getColumn(0).setMaxWidth(39);
            product_table1.getColumnModel().getColumn(3).setMinWidth(60);
            product_table1.getColumnModel().getColumn(3).setMaxWidth(60);
            product_table1.getColumnModel().getColumn(4).setMinWidth(60);
            product_table1.getColumnModel().getColumn(4).setMaxWidth(60);
            product_table1.getColumnModel().getColumn(6).setMinWidth(60);
            product_table1.getColumnModel().getColumn(6).setMaxWidth(60);
        }

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Going to be Incomplete products  :-");

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم القسط", "id_person", "الاسم", "سعر القسط الواحد", "المتبقي"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(customer);

        phone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(phone);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel16)
                    .addContainerGap(549, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(234, 234, 234)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(407, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout All_detailsLayout = new javax.swing.GroupLayout(All_details);
        All_details.setLayout(All_detailsLayout);
        All_detailsLayout.setHorizontalGroup(
            All_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(All_detailsLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        All_detailsLayout.setVerticalGroup(
            All_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(All_detailsLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(All_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 12, -1, 660));

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));

        select_1.setBackground(new java.awt.Color(102, 0, 153));

        select_2.setBackground(new java.awt.Color(102, 0, 153));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Sell a Part for person");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentANDtools/icons8_View_Details_24px.png"))); // NOI18N

        javax.swing.GroupLayout select_2Layout = new javax.swing.GroupLayout(select_2);
        select_2.setLayout(select_2Layout);
        select_2Layout.setHorizontalGroup(
            select_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(select_2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        select_2Layout.setVerticalGroup(
            select_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, select_2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(select_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        select_3.setBackground(new java.awt.Color(102, 0, 153));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Add Products");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentANDtools/icons8_Add_Shopping_Cart_24px.png"))); // NOI18N

        javax.swing.GroupLayout select_3Layout = new javax.swing.GroupLayout(select_3);
        select_3.setLayout(select_3Layout);
        select_3Layout.setHorizontalGroup(
            select_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(select_3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        select_3Layout.setVerticalGroup(
            select_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, select_3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(select_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(25, 25, 25))
        );

        select_4.setBackground(new java.awt.Color(102, 0, 153));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("What Happend Today ");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentANDtools/icons8_Sales_Performance_24px.png"))); // NOI18N

        javax.swing.GroupLayout select_4Layout = new javax.swing.GroupLayout(select_4);
        select_4.setLayout(select_4Layout);
        select_4Layout.setHorizontalGroup(
            select_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(select_4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        select_4Layout.setVerticalGroup(
            select_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, select_4Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(select_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(25, 25, 25))
        );

        select_5.setBackground(new java.awt.Color(102, 0, 153));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("All Details");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentANDtools/icons8_Pass_Fail_64px.png"))); // NOI18N

        javax.swing.GroupLayout select_5Layout = new javax.swing.GroupLayout(select_5);
        select_5.setLayout(select_5Layout);
        select_5Layout.setHorizontalGroup(
            select_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(select_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        select_5Layout.setVerticalGroup(
            select_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, select_5Layout.createSequentialGroup()
                .addGroup(select_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(select_5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(select_5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(102, 0, 153));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Sell Product Cash");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentANDtools/icons8_Request_Money_24px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout select_1Layout = new javax.swing.GroupLayout(select_1);
        select_1.setLayout(select_1Layout);
        select_1Layout.setHorizontalGroup(
            select_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(select_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(select_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(select_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(select_1Layout.createSequentialGroup()
                .addComponent(select_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        select_1Layout.setVerticalGroup(
            select_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, select_1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(select_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select_5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Welcome");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("IN Point of Sale");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("BACK");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(select_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(56, 56, 56))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addComponent(select_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMouseClicked
        int row = customer.getSelectedRow();
        int id = Integer.parseInt(customer.getValueAt(row, 1).toString());
        String query = "select phone from phone where id_person =  " + id;
        go.filltable(query, phone);

    }//GEN-LAST:event_customerMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        SELLPAnnel.setVisible(false);
        All_details.setVisible(false);
        ADDPRODUCT.setVisible(false);
        SaleForPerson.setVisible(false);
       

        buttonGroup1.add(RC);
        buttonGroup1.add(RD);
        buttonGroup1.add(RID);
        buttonGroup1.add(RK);
        buttonGroup1.add(RN);
        buttonGroup1.add(RP);

        buttonGroup2.add(RPNUM);
        buttonGroup2.add(RPNAMe);

        product_table.getTableHeader().setReorderingAllowed(false);
        product_table1.getTableHeader().setReorderingAllowed(false);
        customer.getTableHeader().setReorderingAllowed(false);
        phone.getTableHeader().setReorderingAllowed(false);

    }//GEN-LAST:event_formWindowOpened

    private void searchkeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchkeyKeyPressed

    }//GEN-LAST:event_searchkeyKeyPressed

    private void searchkeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchkeyKeyReleased
        String query = "select * from product where ";
        if (RD.isSelected()) {
            query += "discribe ";
        }
        if (RID.isSelected()) {
            query += "id_product ";
        }
        if (RN.isSelected()) {
            query += "NUMBER ";
        }
        if (RP.isSelected()) {
            query += "price ";
        }
        if (RC.isSelected()) {
            query += "comment ";

        }
        if (RK.isSelected()) {
            query += "kind ";

        }

        query += "like '%" + searchkey.getText() + "%'";
        product p = new product();

        p.getCustomrow(query, TB);

    }//GEN-LAST:event_searchkeyKeyReleased

    private void searchkeyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchkeyKeyTyped

    }//GEN-LAST:event_searchkeyKeyTyped

    private void TBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBMouseClicked
        int row = TB.getSelectedRow();
        int idd = Integer.parseInt(TB.getValueAt(row, 0).toString());
        id.setEnabled(false);
        id.setText(idd + "");


    }//GEN-LAST:event_TBMouseClicked

    private void bottonblue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonblue1ActionPerformed
        product p = new product();
        p.addproduct(Integer.parseInt(id.getText()), Integer.parseInt(num.getText()));
        id.setText("");
        num.setText("");
        p.getallrows(TB);

    }//GEN-LAST:event_bottonblue1ActionPerformed

    private void PERsonPArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PERsonPArtMouseClicked

        int row = PERsonPArt.getSelectedRow();
        int id = Integer.parseInt(PERsonPArt.getValueAt(row, 0).toString());
        IDPART.setText(id + "");


    }//GEN-LAST:event_PERsonPArtMouseClicked

    private void bottonblue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonblue2ActionPerformed
        boolean x = Tools.confirmMSG("are you sure to do this Process");
        if (x) {
            int idd = Integer.parseInt(IDPART.getText());
            int priCE = Integer.parseInt(price.getText());
            part p = new part();
            p.paypart(idd);
        } else {
            price.setText("");
            IDPART.setText("");

        }
        price.setText("");
        IDPART.setText("");
    }//GEN-LAST:event_bottonblue2ActionPerformed

    private void SKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SKKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SKKeyPressed

    private void SKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SKKeyReleased
        String query = "select * from product where ";
        if (RDD.isSelected()) {
            query += "discribe ";
        }
        if (RIDD.isSelected()) {
            query += "id_product ";
        }
        if (RNN.isSelected()) {
            query += "NUMBER ";
        }
        if (RPP.isSelected()) {
            query += "price ";
        }
        if (RCC.isSelected()) {
            query += "comment ";

        }
        if (RKK.isSelected()) {
            query += "kind ";

        }

        query += "like '%" + SK.getText() + "%'";
        product p = new product();

        p.getCustomrow(query, tBforsell);


    }//GEN-LAST:event_SKKeyReleased

    private void SKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SKKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_SKKeyTyped

    private void TBBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBBMouseClicked

    private void tBforsellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBforsellMouseClicked

        int row = tBforsell.getSelectedRow();

        String id = tBforsell.getValueAt(row, 0).toString();
        if (cheek_in_table(TBB, id)) {
            Tools.msgBox("هذا العنصر بالفعل موجود قن بالتعديل علية داخل الجدول");

        } else {
            id1.setText(id);
            id1.setEnabled(false);
            tBforsell.setEnabled(false);
        }

    }//GEN-LAST:event_tBforsellMouseClicked

    private void RIDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RIDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RIDDActionPerformed

    private void bottonblue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonblue3ActionPerformed
        int row = tBforsell.getSelectedRow();
        boolean b = true;
        String Comment;
        String discrib;
        String kind;
        String Pricee;
        int Rnum;
        int num = Integer.parseInt(num1.getText());
        String id = id1.getText();

        discrib = tBforsell.getValueAt(row, 2).toString();
        kind = tBforsell.getValueAt(row, 1).toString();
        Rnum = Integer.parseInt(tBforsell.getValueAt(row, 3).toString());
        Pricee = tBforsell.getValueAt(row, 4).toString();
        while (b) {
            if (Rnum >= num) {
                String n = num + "";
                DefaultTableModel mode6 = (DefaultTableModel) TBB.getModel();
                String[] data = {id, kind, discrib, n, Pricee};
                mode6.addRow(data);

                b = false;
                id1.setText("");
                num1.setText("");
                tBforsell.setEnabled(true);
            } else {
                Tools.msgBox("هذا السعر اعلي من الموجود");
            }
            b = false;
        }

    }//GEN-LAST:event_bottonblue3ActionPerformed

    private void bottonRamady11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonRamady11ActionPerformed
        id1.setText("");
        num1.setText("");
        tBforsell.setEnabled(true);
    }//GEN-LAST:event_bottonRamady11ActionPerformed

    private void bottongreen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottongreen1ActionPerformed
        if (Tools.confirmMSG("هل انت واثق من اتمام عملية البيع")) {
            double sum = 0;
            if (!Tools.isEmpty(TBB)) {
                Tools.msgBox(TBB.getRowCount() + "");
                int rows = TBB.getRowCount();
                for (int i = 0; i < rows; i++) {
                    String id = TBB.getValueAt(0, 0).toString();
                    String number = TBB.getValueAt(0, 3).toString();
                    double price = Double.parseDouble(TBB.getValueAt(0, 4).toString());
                    String s = "SELECT NUMBER FROM `product` WHERE id_product=" + id;
                    db.go.filltable(s, TT);
                    int num1 = Integer.parseInt(number);

                    int num2 = Integer.parseInt(TT.getValueAt(0, 0).toString());

                    if (num2 >= num1) {
                        String stat = "UPDATE `product` SET `NUMBER` = NUMBER-" + number + " WHERE `product`.`id_product` =" + id;
                        db.go.runstatment(stat);

                        DefaultTableModel mode1 = (DefaultTableModel) TBB.getModel();

                        sum = sum + (num1 * price);

                        mode1.removeRow(0);
                    } else {
                        Tools.msgBox("هناك عنصر عددة اكبر من المتاح  \n تمت عملية البيع علي العناصر الاخري عدا ما في الجدول \n لن تباع حتي يتم التعديل \n سعر المباع اسفل");
                    }
                }
                sellnum.setText(sum + "");
            } else {
                Tools.msgBox("الجدول فاضي هه");
                sellnum.setText(sum + "");
            }

        }
    }//GEN-LAST:event_bottongreen1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        SELLPAnnel.setVisible(false);
        All_details.setVisible(false);
        ADDPRODUCT.setVisible(false);
        SaleForPerson.setVisible(true);
       
        String query = "SELECT id,id_person, `الاسم`, `سعر القسط الواحد`, `FT`, `remainder`,`اخر قسط`, `المدة كاملة` FROM `customer_dataa`";
        go.filltable(query, PERsonPArt);

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        SELLPAnnel.setVisible(false);
        All_details.setVisible(false);
        ADDPRODUCT.setVisible(true);
        SaleForPerson.setVisible(false);
       
        ///////////////////////////////////
        product p = new product();
        p.getallrows(TB);

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        SELLPAnnel.setVisible(false);
        All_details.setVisible(false);
        ADDPRODUCT.setVisible(false);
        SaleForPerson.setVisible(false);
      
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        SELLPAnnel.setVisible(false);
        All_details.setVisible(true);
        ADDPRODUCT.setVisible(false);
        SaleForPerson.setVisible(false);
       

        /////////////////////////product////////////////
        String query = "select * from product where number = 0 ";
        go.filltable(query, product_table);
        /////////////////////////product////////////////
        query = "select * from product where number = 1 ";
        go.filltable(query, product_table1);
        ///////////////////////////////////////////////
        query = "SELECT id,id_person,customer_dataa.الاسم,`سعر القسط الواحد`,customer_dataa.remainder FROM customer_dataa WHERE customer_dataa.remainder>=TRUNCATE((DATEDIFF(customer_dataa.FT,CURDATE())/30),0) ";
        go.filltable(query, customer);
        //////////////////////////////////////////////
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        buttonGroup1.add(RDD);
        buttonGroup1.add(RIDD);
        buttonGroup1.add(RNN);
        buttonGroup1.add(RPP);
        buttonGroup1.add(RCC);
        buttonGroup1.add(RKK);
        SELLPAnnel.setVisible(true);
        All_details.setVisible(false);
        ADDPRODUCT.setVisible(false);
        SaleForPerson.setVisible(false);
       

        product p = new product();
        //        clear();

        tBforsell.getTableHeader().setReorderingAllowed(false);
        p.getallrows(tBforsell);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       new daily().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ADDPRODUCT;
    private javax.swing.JPanel All_details;
    private javax.swing.JLabel IDPART;
    private javax.swing.JTable PERsonPArt;
    private javax.swing.JRadioButton RC;
    private javax.swing.JRadioButton RCC;
    private javax.swing.JRadioButton RD;
    private javax.swing.JRadioButton RDD;
    private javax.swing.JRadioButton RID;
    private javax.swing.JRadioButton RIDD;
    private javax.swing.JRadioButton RK;
    private javax.swing.JRadioButton RKK;
    private javax.swing.JRadioButton RN;
    private javax.swing.JRadioButton RNN;
    private javax.swing.JRadioButton RP;
    private javax.swing.JRadioButton RPNAMe;
    private javax.swing.JRadioButton RPNUM;
    private javax.swing.JRadioButton RPP;
    private javax.swing.JPanel SELLPAnnel;
    private javax.swing.JTextField SK;
    private javax.swing.JPanel SaleForPerson;
    private javax.swing.JTable TB;
    private javax.swing.JTable TBB;
    private javax.swing.JTable TT;
    private componentANDtools.bottonRamady1 bottonRamady11;
    private componentANDtools.bottonblue bottonblue1;
    private componentANDtools.bottonblue bottonblue2;
    private componentANDtools.bottonblue bottonblue3;
    private componentANDtools.bottongreen bottongreen1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTable customer;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField num;
    private javax.swing.JTextField num1;
    private javax.swing.JTable phone;
    private javax.swing.JTextField price;
    private javax.swing.JTable product_table;
    private javax.swing.JTable product_table1;
    private javax.swing.JTextField searchkey;
    private javax.swing.JPanel select_1;
    private javax.swing.JPanel select_2;
    private javax.swing.JPanel select_3;
    private javax.swing.JPanel select_4;
    private javax.swing.JPanel select_5;
    private javax.swing.JLabel sellnum;
    private javax.swing.JTable tBforsell;
    // End of variables declaration//GEN-END:variables

    private boolean cheek_in_table(JTable table, String sk) {
        DefaultTableModel mode1 = (DefaultTableModel) table.getModel();
        for (int i = 0; i < table.getRowCount(); i++) {
            if (sk.equals(table.getValueAt(i, 0).toString())) {
                return true;
            }

        }

        return false;

    }
}
