/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMS;

import Entyty.customers;
import Entyty.person;
import Entyty.phone;
import Entyty.product;
import componentANDtools.Tools;
import componentANDtools.textfeild;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Abdelmoneam Ismael
 */
public class PERSON extends javax.swing.JFrame {

    /**
     * Creates new form Mainframe
     */
    public PERSON() {
        getContentPane().setBackground(Color.white);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ADDB = new componentANDtools.bottonC111();
        jLabel3 = new javax.swing.JLabel();
        DELETEB = new componentANDtools.bottonCP();
        jLabel4 = new javax.swing.JLabel();
        UPDATEB = new componentANDtools.bottonRamady1();
        jLabel5 = new javax.swing.JLabel();
        TID = new textfeild(15);
        FINDB = new componentANDtools.bottonburble11();
        TN = new textfeild(15);
        ALLB = new componentANDtools.bottongreen();
        TAD = new textfeild(15);
        TC = new textfeild(15);
        jLabel10 = new javax.swing.JLabel();
        phontext = new javax.swing.JTextField();
        addphone = new componentANDtools.bottonblue();
        removephone = new componentANDtools.bottonblue();
        jLabel11 = new javax.swing.JLabel();
        compo1 = new componentANDtools.compo();
        jLabel7 = new javax.swing.JLabel();
        RN = new javax.swing.JRadioButton();
        RID = new javax.swing.JRadioButton();
        RAD = new javax.swing.JRadioButton();
        RC = new javax.swing.JRadioButton();
        RP = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchkey = new textfeild(15);
        searchB = new componentANDtools.bottonblue();
        backB = new componentANDtools.bottonblue();
        Timebeg = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Ladress = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Lcomment = new javax.swing.JLabel();
        Lname = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        number_of_part = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Time_bagain = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        REmainder = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Price_of_part = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Last_price_of_part = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ALL_period = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        End_time = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        test = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        state = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Welcome ");

        jPanel1.setBackground(Color.WHITE);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Person\n"));

        jPanel2.setBackground(Color.WHITE);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("ID");

        ADDB.setText("ADD");
        ADDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDBActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("الاسم");

        DELETEB.setText("DELETE");
        DELETEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEBActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("العنوان");

        UPDATEB.setText("UPDATE");
        UPDATEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("تعليق");

        FINDB.setText("Clear");
        FINDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINDBActionPerformed(evt);
            }
        });

        ALLB.setText("ALL");
        ALLB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALLBActionPerformed(evt);
            }
        });

        jLabel10.setText("phones");

        addphone.setText("ADD");
        addphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addphoneActionPerformed(evt);
            }
        });

        removephone.setText("Remove");
        removephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removephoneActionPerformed(evt);
            }
        });

        jLabel11.setText("status :-");

        compo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "contacts", "موزع للبضائع", "ياخذ منا بضائع" }));
        compo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(compo1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ALLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FINDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UPDATEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(DELETEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(ADDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TC, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TN, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TAD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(phontext, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(removephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8))))
                        .addGap(42, 42, 42))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(phontext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(compo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELETEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UPDATEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FINDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("البحث بواسطة :-");

        RN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RN.setText("الاسم");

        RID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RID.setText("ID");

        RAD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RAD.setText("العنوان");

        RC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RC.setText("comment");

        RP.setText("phone");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "الاسم", "العنوان", "التعليق"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        searchkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchkeyActionPerformed(evt);
            }
        });
        searchkey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchkeyKeyReleased(evt);
            }
        });

        searchB.setText("بحث");
        searchB.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });

        backB.setText("BACK");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });

        Timebeg.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("name :");

        jLabel9.setText("adress:");

        jLabel12.setText("comment :");

        jLabel13.setText("number of part :");

        number_of_part.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        number_of_part.setForeground(new java.awt.Color(51, 0, 255));

        jLabel15.setText("Time begain :");

        Time_bagain.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Time_bagain.setForeground(new java.awt.Color(51, 0, 255));

        jLabel17.setText("remainder :");

        REmainder.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        REmainder.setForeground(new java.awt.Color(51, 0, 255));

        jLabel19.setText("price of part :");

        Price_of_part.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Price_of_part.setForeground(new java.awt.Color(51, 0, 255));

        jLabel21.setText("last price of part:");

        Last_price_of_part.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Last_price_of_part.setForeground(new java.awt.Color(51, 0, 255));

        jLabel23.setText("all period");

        ALL_period.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ALL_period.setForeground(new java.awt.Color(51, 0, 255));

        jLabel25.setText("end time");

        End_time.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        End_time.setForeground(new java.awt.Color(51, 0, 255));

        TP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TP);

        jTable2.setForeground(new java.awt.Color(102, 0, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الوصف", "النوع"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        jLabel8.setText("Status :");

        javax.swing.GroupLayout TimebegLayout = new javax.swing.GroupLayout(Timebeg);
        Timebeg.setLayout(TimebegLayout);
        TimebegLayout.setHorizontalGroup(
            TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimebegLayout.createSequentialGroup()
                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimebegLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(TimebegLayout.createSequentialGroup()
                                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TimebegLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(TimebegLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Lcomment, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ladress, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(TimebegLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimebegLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number_of_part, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(REmainder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TimebegLayout.createSequentialGroup()
                        .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(TimebegLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Last_price_of_part, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(TimebegLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(Time_bagain, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ALL_period, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimebegLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Price_of_part, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TimebegLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(End_time, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TimebegLayout.setVerticalGroup(
            TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimebegLayout.createSequentialGroup()
                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(Ladress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(Lcomment, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(TimebegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(number_of_part, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(REmainder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Price_of_part, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimebegLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(End_time, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(TimebegLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(Last_price_of_part, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(TimebegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(Time_bagain, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(ALL_period, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        test.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        jScrollPane4.setViewportView(test);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        state.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane5.setViewportView(state);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Timebeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(223, 223, 223))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(RC)
                        .addGap(18, 18, 18)
                        .addComponent(RP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RAD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RID)
                        .addGap(18, 18, 18)
                        .addComponent(RN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(searchkey, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(searchB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(RN)
                            .addComponent(RID)
                            .addComponent(RAD)
                            .addComponent(RC)
                            .addComponent(RP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGap(6, 6, 6)
                .addComponent(Timebeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(547, 547, 547))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALLBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALLBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        buttonGroup1.add(RN);
        buttonGroup1.add(RID);
        buttonGroup1.add(RAD);
        buttonGroup1.add(RP);
        buttonGroup1.add(RC);
        person p = new person();
        p.getallrows(jTable1);
        clear();
        TID.setEnabled(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        test.getTableHeader().setReorderingAllowed(false);


    }//GEN-LAST:event_formWindowOpened

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBActionPerformed

    private void ADDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDBActionPerformed
        person p = new person();
        p.setId_person(Integer.parseInt(TID.getText()));
        p.setName(TN.getText());
        p.setAdress(TAD.getText());
        p.setComment(TC.getText());
        
        String msg = (String) compo1.getSelectedItem();
        p.setStatus(msg);

        p.add();
        clear();
        p.getallrows(jTable1);
         
        
        
        
        
    }//GEN-LAST:event_ADDBActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        clear();
        int row = jTable1.getSelectedRow();
        String comment;
        String adress;
        String name;

        String id = jTable1.getValueAt(row, 0).toString();
        TID.setText(id);
        phone ph = new phone();
        ph.getallbyid(Integer.parseInt(jTable1.getValueAt(row, 0).toString()), TP);

        if (jTable1.getValueAt(row, 1) != null) {
            name = jTable1.getValueAt(row, 1).toString();
            TN.setText(name);
            Lname.setText(name);
        } else {
            TN.setText("");
            Lname.setText("");

        }

        if (jTable1.getValueAt(row, 2) != null) {
            adress = jTable1.getValueAt(row, 2).toString();
            TAD.setText(adress);
            Ladress.setText(adress);
        } else {
            TAD.setText("");
            Ladress.setText("");
        }

        if (jTable1.getValueAt(row, 3) != null) {
            comment = jTable1.getValueAt(row, 3).toString();
            TC.setText(comment);
            Lcomment.setText(comment);
        } else {
            TC.setText("");
            Lcomment.setText("");
        }
       
        Details(id);

        DELETEB.setEnabled(true);
        UPDATEB.setEnabled(true);
        ADDB.setEnabled(false);
        addphone.setEnabled(true);
        removephone.setEnabled(false);
        phontext.setEnabled(true);
        compo1.setEnabled(false);
         

    }//GEN-LAST:event_jTable1MouseClicked

    private void FINDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINDBActionPerformed
        clear();
        ADDB.setEnabled(true);
        DELETEB.setEnabled(false);
        UPDATEB.setEnabled(false);
        addphone.setEnabled(false);
        removephone.setEnabled(false);
        phontext.setEnabled(false);
        
        
    }//GEN-LAST:event_FINDBActionPerformed

    private void UPDATEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEBActionPerformed
        person p = new person();
        if (Tools.confirmMSG("do you want to update ?")) {
            p.setName(TN.getText());
            p.setAdress(TAD.getText());
            p.setComment(TC.getText());

            p.update(Integer.parseInt(TID.getText()));
            p.getallrows(jTable1);
            clear();
        }
    }//GEN-LAST:event_UPDATEBActionPerformed

    private void DELETEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEBActionPerformed
        person p = new person();
        if (Tools.confirmMSG("do you want to delete ?")) {

            p.delete(Integer.parseInt(TID.getText()));
            p.getallrows(jTable1);
            clear();
        }
    }//GEN-LAST:event_DELETEBActionPerformed

    private void searchkeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchkeyKeyReleased
        String query = "select * from persone where ";

        if (RID.isSelected()) {
            query += "id_person ";
            query += "like '%" + searchkey.getText() + "%'";
            product p = new product();
          
            p.getCustomrow(query, jTable1);
        }
        if (RN.isSelected()) {
            query += "name ";
            query += "like '%" + searchkey.getText() + "%'";
            product p = new product();
           
            p.getCustomrow(query, jTable1);
        }
        if (RP.isSelected()) {
            query = "select phone from phone where phone like '%" + searchkey.getText() + "%'";
            phone p = new phone();
            p.getCustomrow(query, TP);

        }
        if (RC.isSelected()) {
            query += "comment ";
            query += "like '%" + searchkey.getText() + "%'";
            product p = new product();
         
            p.getCustomrow(query, jTable1);

        }
        if (RAD.isSelected()) {
            query += "adress ";

            query += "like '%" + searchkey.getText() + "%'";
            product p = new product();
         
            p.getCustomrow(query, jTable1);
        }else{
            JOptionPane.showMessageDialog(null, "حدد نوع البحث بقي     (:");
        
        }


    }//GEN-LAST:event_searchkeyKeyReleased

    private void searchkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchkeyActionPerformed

    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        String query = "select * from persone where ";

        if (RID.isSelected()) {
            query += "id_person ";
        }
        if (RN.isSelected()) {
            query += "name ";
        }
//        if(RP.isSelected()){
//            query +="phone ";
//        }
        if (RC.isSelected()) {
            query += "comment ";

        }
        if (RAD.isSelected()) {
            query += "adress ";

        }

        query += "like '%" + searchkey.getText() + "%'";
        product p = new product();
      
        p.getCustomrow(query, jTable1);

    }//GEN-LAST:event_searchBActionPerformed

    private void TPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPMouseClicked
       
       int row=TP.getSelectedRow();
       String select=TP.getValueAt(row, 0).toString();
       phontext.setText(select);
       removephone.setEnabled(true);
        
        
        
    }//GEN-LAST:event_TPMouseClicked

    private void addphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addphoneActionPerformed
        int row=jTable1.getSelectedRow();
        int id=Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        String phoString=phontext.getText();
       
        String query
               ="INSERT INTO `phone` (`id_person`, `phone`, `comment`) VALUES ("+id+", '"+phoString+"', '')";
       db.go.runstatment(query);
       phone p=new phone();
       p.getallbyid(id, TP);
       phontext.setText("");
       
    }//GEN-LAST:event_addphoneActionPerformed

    private void removephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removephoneActionPerformed
       int row=jTable1.getSelectedRow();
       int id=Integer.parseInt(jTable1.getValueAt(row, 0).toString());
       String phoString=phontext.getText();
       
       
       String query
               ="DELETE FROM `phone` WHERE `phone`.`id_person` = "+id+" AND `phone`.`phone` ="+phoString; 
       db.go.runstatment(query);
       phone p=new phone();
       p.getallbyid(id, TP);
       phontext.setText("");
    }//GEN-LAST:event_removephoneActionPerformed

    private void compo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compo1ActionPerformed
       
    }//GEN-LAST:event_compo1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
         int row=jTable2.getSelectedRow();
       String select=TP.getValueAt(row, 0).toString();
       phontext.setText(select);
       removephone.setEnabled(true);
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PERSON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PERSON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PERSON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PERSON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PERSON().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentANDtools.bottonC111 ADDB;
    private componentANDtools.bottongreen ALLB;
    private javax.swing.JLabel ALL_period;
    private componentANDtools.bottonCP DELETEB;
    private javax.swing.JLabel End_time;
    private componentANDtools.bottonburble11 FINDB;
    private javax.swing.JLabel Ladress;
    private javax.swing.JLabel Last_price_of_part;
    private javax.swing.JLabel Lcomment;
    private javax.swing.JLabel Lname;
    private javax.swing.JLabel Price_of_part;
    private javax.swing.JRadioButton RAD;
    private javax.swing.JRadioButton RC;
    private javax.swing.JLabel REmainder;
    private javax.swing.JRadioButton RID;
    private javax.swing.JRadioButton RN;
    private javax.swing.JRadioButton RP;
    private javax.swing.JTextField TAD;
    private javax.swing.JTextField TC;
    private javax.swing.JTextField TID;
    private javax.swing.JTextField TN;
    private javax.swing.JTable TP;
    private javax.swing.JLabel Time_bagain;
    private javax.swing.JPanel Timebeg;
    private componentANDtools.bottonRamady1 UPDATEB;
    private componentANDtools.bottonblue addphone;
    private componentANDtools.bottonblue backB;
    private javax.swing.ButtonGroup buttonGroup1;
    private componentANDtools.compo compo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel number_of_part;
    private javax.swing.JTextField phontext;
    private componentANDtools.bottonblue removephone;
    private componentANDtools.bottonblue searchB;
    private javax.swing.JTextField searchkey;
    private javax.swing.JTable state;
    private javax.swing.JLabel status;
    private javax.swing.JTable test;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        TID.setText("");
        TN.setText("");
        TAD.setText("");
        TC.setText("");
        person p = new person();
        DELETEB.setEnabled(false);
        UPDATEB.setEnabled(false);
        addphone.setEnabled(false);
        removephone.setEnabled(false);
        phontext.setEnabled(false);
        TID.setText(p.autonumbers());
        TN.requestFocus();
        compo1.setEnabled(true);
       

    }

    private void Details(String id) {
        number_of_part.setText("");
        ALL_period.setText("");
        Time_bagain.setText("");
        Last_price_of_part.setText("");
        End_time.setText("");
        Price_of_part.setText("");
        status.setText("");
        String state = "SELECT state FROM `status` where id_person=" + id;
        if (db.go.runstatment(state)) {
            db.go.filltable(state, this.state);
            int row = jTable1.getSelectedRow();
            status.setText(this.state.getValueAt(0, 0).toString());
            if (status.getText().equals("مربوط بقسط")) {
                customers p = new customers();
                String quiry = "select discribe,kind from customer_dataa where id_person =" + id;
                p.getCustomrow(quiry, jTable2);
                p.getallbyid(Integer.parseInt(jTable1.getValueAt(row, 0).toString()), test);
                String string;

                if (Tools.isEmpty(test)) {
                   
                } else {

                    if (test.getValueAt(0, 0).toString() != null) {
                        string = test.getValueAt(0, 0).toString();
                        number_of_part.setText(string);

                    } else {

                        number_of_part.setText("");
                    }
                    if (test.getValueAt(0, 3).toString() != null) {
                        string = test.getValueAt(0, 3).toString();
                        Price_of_part.setText(string);

                    } else {

                        Price_of_part.setText("");
                    }
                    if (test.getValueAt(0, 4).toString() != null) {
                        string = test.getValueAt(0, 4).toString();
                        End_time.setText(string);

                    } else {

                        End_time.setText("");
                    }
                    if (test.getValueAt(0, 7).toString() != null) {
                        string = test.getValueAt(0, 7).toString();
                        Time_bagain.setText(string);

                    } else {

                        Time_bagain.setText("");
                    }
                    if (test.getValueAt(0, 8).toString() != null) {
                        string = test.getValueAt(0, 8).toString();
                        ALL_period.setText(string);

                    } else {

                        ALL_period.setText("");
                    }
                    if (test.getValueAt(0, 9).toString() != null) {
                        string = test.getValueAt(0, 9).toString();
                        Last_price_of_part.setText(string);

                    } else {

                        Last_price_of_part.setText("");
                    }
                    if (test.getValueAt(0, 10).toString() != null) {
                        string = test.getValueAt(0, 10).toString();
                        REmainder.setText(string);

                    } else {

                        REmainder.setText("");
                    }

                    string = "select discribe,kind from customer_dataa where id_person =" + id;
                    p.getCustomrow(string, jTable2);

                }
            }
            if (status.getText().equals("موزع للبضائع")) {
                customers p = new customers();
                String quiry = "SELECT discribe,kind FROM `suppliers_data` WHERE id_person=" + id;
                p.getCustomrow(quiry, jTable2);
                

            }
            if (status.getText().equals("contacts")) {
                customers p = new customers();
                String quiry = "SELECT discribe,kind FROM `suppliers_data` WHERE id_person=" + id;
                p.getCustomrow(quiry, jTable2);

            }

            if (status.getText().equals("ياخذ منا بضائع")) {
                customers p = new customers();
                String quiry = "SELECT discribe,kind FROM `suppliers_data` WHERE id_person=" + id;
                p.getCustomrow(quiry, jTable2);

            }

        }

    }

}
