/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMS;

import Entyty.customers;
import Entyty.person;
import Entyty.phone;
import Entyty.product;
import componentANDtools.textfeild;
import db.go;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdelmoneam Ismael
 */
public class suppliers extends javax.swing.JFrame {

    /**
     * Creates new form suppliers
     */
    public suppliers() {
        getContentPane().setBackground(Color.white);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bottonblue1 = new componentANDtools.bottonblue();
        jLabel7 = new javax.swing.JLabel();
        RN = new javax.swing.JRadioButton();
        RID = new javax.swing.JRadioButton();
        RAD = new javax.swing.JRadioButton();
        RC = new javax.swing.JRadioButton();
        searchB = new componentANDtools.bottonblue();
        searchkey = new textfeild(15);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backB = new componentANDtools.bottonblue();
        jScrollPane3 = new javax.swing.JScrollPane();
        TP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        bottonblue2 = new componentANDtools.bottonblue();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TB = new javax.swing.JTable();
        bottonblue3 = new componentANDtools.bottonblue();
        RC1 = new javax.swing.JRadioButton();
        RP = new javax.swing.JRadioButton();
        RN1 = new javax.swing.JRadioButton();
        RID1 = new javax.swing.JRadioButton();
        RD = new javax.swing.JRadioButton();
        RK = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        Psearch = new textfeild(15);
        searchB1 = new componentANDtools.bottonblue();
        bottonblue4 = new componentANDtools.bottonblue();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bottonblue1.setText("ADD");
        bottonblue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonblue1ActionPerformed(evt);
            }
        });
        jPanel1.add(bottonblue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 73, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("البحث بواسطة :-");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        RN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RN.setText("الاسم");
        jPanel1.add(RN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        RID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RID.setText("ID");
        jPanel1.add(RID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        RAD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RAD.setText("العنوان");
        jPanel1.add(RAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        RC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RC.setText("comment");
        jPanel1.add(RC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        searchB.setText("بحث");
        searchB.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });
        jPanel1.add(searchB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 72, -1));

        searchkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchkeyActionPerformed(evt);
            }
        });
        searchkey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchkeyKeyReleased(evt);
            }
        });
        jPanel1.add(searchkey, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 224, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "الاسم", "العنوان", "التعليق"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 340, 237));

        backB.setText("BACK");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        jPanel1.add(backB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 87, -1));

        TP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TP);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 189, 102));

        jTable2.setForeground(new java.awt.Color(102, 0, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_product", "الوصف", "النوع"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(50);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 445, 129));

        jCheckBox1.setText("اضافة منتج جديد");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, -1, -1));

        bottonblue2.setText("حذف المحدد");
        bottonblue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonblue2ActionPerformed(evt);
            }
        });
        jPanel1.add(bottonblue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "النوع", "الوصف", "العدد", "السعر", "تعليق"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TB);
        if (TB.getColumnModel().getColumnCount() > 0) {
            TB.getColumnModel().getColumn(2).setMinWidth(180);
            TB.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        bottonblue3.setText("اضافة للموزع");
        bottonblue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonblue3ActionPerformed(evt);
            }
        });

        RC1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RC1.setText("comment");

        RP.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RP.setText("السعر");

        RN1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RN1.setText("العدد");

        RID1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RID1.setText("ID");

        RD.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RD.setText("الاسم");

        RK.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RK.setText("النوع");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("البحث بواسطة :-");

        Psearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PsearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PsearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PsearchKeyTyped(evt);
            }
        });

        searchB1.setText("بحث");
        searchB1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        searchB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RC1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Psearch, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchB1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RP)
                        .addGap(9, 9, 9)
                        .addComponent(RN1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RID1)
                        .addGap(18, 18, 18)
                        .addComponent(RD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RK)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bottonblue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(bottonblue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(RD)
                            .addComponent(RID1)
                            .addComponent(RN1)
                            .addComponent(RP)
                            .addComponent(RC1)
                            .addComponent(RK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Psearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 930, 240));

        bottonblue4.setText("عرض من جديد");
        bottonblue4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonblue4ActionPerformed(evt);
            }
        });
        jPanel1.add(bottonblue4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Welcome ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(380, 380, 380))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonblue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonblue1ActionPerformed
        this.dispose();
        new PERSON().setVisible(true);
    }//GEN-LAST:event_bottonblue1ActionPerformed

    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        String query = "select * from persone where ";

        if (RID.isSelected()) {
            query += "id_person ";
        }
        if (RN.isSelected()) {
            query += "name ";
        }
        //        if(RP.isSelected()){
        //            query +="phone ";
        //        }
        if (RC.isSelected()) {
            query += "comment ";

        }
        if (RAD.isSelected()) {
            query += "adress ";

        }

        query += "like '%" + searchkey.getText() + "%'";
        product p = new product();
        System.out.println(query);
        p.getCustomrow(query, jTable1);
    }//GEN-LAST:event_searchBActionPerformed

    private void searchkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchkeyActionPerformed

    private void searchkeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchkeyKeyReleased
        
        String query = "SELECT * FROM `suppliers_dataa` where";
        

        if (RID.isSelected()) {
            query += " id_person ";
            query += "like '%" + searchkey.getText() + "%'";
            System.out.println(query
            );
            
            db.go.filltable(query,jTable1);
        }
        if (RN.isSelected()) {
            query += " name ";
            query += "like '%" + searchkey.getText() + "%'";
            product p = new product();
            System.out.println(query);
            p.getCustomrow(query, jTable1);
        }
       
        if (RC.isSelected()) {
            query += " comment ";
            query += "like '%" + searchkey.getText() + "%'";
            product p = new product();
            System.out.println(query);
            p.getCustomrow(query, jTable1);

        }
        if (RAD.isSelected()) {
            query += " adress ";

            query += "like '%" + searchkey.getText() + "%'";
            product p = new product();
            System.out.println(query);
            p.getCustomrow(query, jTable1);
        }else{
            JOptionPane.showMessageDialog(null, "ارجوك ارجوك تحدد نوع البحث");
        
        }

    }//GEN-LAST:event_searchkeyKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
jCheckBox1.setEnabled(true);
        ///////////////////////////////////  
        int row = jTable1.getSelectedRow();
        System.out.println(row);
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        ////////////////////////////////
        phone ph = new phone();
        ph.getallbyid(id, TP);
        ////////////////////////////////
        customers p = new customers();
        String quiry = "SELECT id_product,discribe,kind FROM `suppliers_data` WHERE id_person=" + id;
        p.getCustomrow(quiry, jTable2);


    }//GEN-LAST:event_jTable1MouseClicked

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBActionPerformed

    private void TPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPMouseClicked

//        int row=TP.getSelectedRow();
//        String select=TP.getValueAt(row, 0).toString();
//        phontext.setText(select);
//        removephone.setEnabled(true);

    }//GEN-LAST:event_TPMouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

//int row=jTable2.getSelectedRow();
//        String select=TP.getValueAt(row, 0).toString();
//        phontext.setText(select);
//        removephone.setEnabled(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void bottonblue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonblue2ActionPerformed
        int row = jTable1.getSelectedRow();
        System.out.println(row);
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        int id_product = Integer.parseInt(jTable2.getValueAt(row, 0).toString());
        String quiry = "DELETE FROM `suppliers` WHERE `suppliers`.`id_person` =" + id + " AND `suppliers`.`id_product` = " + id_product;
        db.go.runstatment(quiry);
        customers p = new customers();
        quiry = "SELECT id_product,discribe,kind FROM `suppliers_data` WHERE id_person=" + id;
        p.getCustomrow(quiry, jTable2);

    }//GEN-LAST:event_bottonblue2ActionPerformed

    private void TBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBMouseClicked


    }//GEN-LAST:event_TBMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jPanel2.setVisible(true);
            product p=new product();
            p.getallrows(TB);
            
            bottonblue2.setEnabled(false);
            
            
        } else {
            jPanel2.setVisible(false);
            bottonblue2.setEnabled(true);
                    
        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jPanel2.setVisible(false);
        String query = "SELECT * FROM `suppliers_dataa`";
        db.go.filltable(query, jTable1);
        jCheckBox1.setEnabled(false);
         buttonGroup1.add(RN);
        buttonGroup1.add(RID);
        buttonGroup1.add(RAD);
      
        buttonGroup1.add(RC);
        
        buttonGroup2.add(RD);
        buttonGroup2.add(RID);
        buttonGroup2.add(RN);
        buttonGroup2.add(RP);
        buttonGroup2.add(RC);
        buttonGroup2.add(RK);
        
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        TB.getTableHeader().setReorderingAllowed(false); 
        TP.getTableHeader().setReorderingAllowed(false);
    }//GEN-LAST:event_formWindowOpened

    private void bottonblue4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonblue4ActionPerformed
       String query = "SELECT * FROM `suppliers_dataa`";
        db.go.filltable(query, jTable1);
         product p=new product();
            p.getallrows(TB);
    }//GEN-LAST:event_bottonblue4ActionPerformed

    private void bottonblue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonblue3ActionPerformed
      int row=TB.getSelectedRow();
      int id_product=Integer.parseInt(TB.getValueAt(row,0).toString());
      int id_person=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
      String quiry="INSERT INTO `suppliers` (`id_person`, `id_product`) VALUES ('"+id_person+"', '"+id_product+"');";
         if(db.go.runstatment(quiry)){
         JOptionPane.showMessageDialog(null, "عنصر متكرر");
         }
         customers p = new customers();
         quiry = "SELECT id_product,discribe,kind FROM `suppliers_data` WHERE id_person=" + id_person;
        p.getCustomrow(quiry, jTable2);
    }//GEN-LAST:event_bottonblue3ActionPerformed

    private void PsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PsearchKeyPressed

    }//GEN-LAST:event_PsearchKeyPressed

    private void PsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PsearchKeyReleased
        String query = "select * from product where ";
        if (RD.isSelected()) {
            query += "discribe ";
        }
        if (RID.isSelected()) {
            query += "id_product ";
        }
        if (RN.isSelected()) {
            query += "NUMBER ";
        }
        if (RP.isSelected()) {
            query += "price ";
        }
        if (RC.isSelected()) {
            query += "comment ";

        }
        if (RK.isSelected()) {
            query += "kind ";

        }

        query += "like '%" + Psearch.getText() + "%'";
        product p = new product();
        System.out.println(query);
        p.getCustomrow(query, TB);

    }//GEN-LAST:event_PsearchKeyReleased

    private void PsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PsearchKeyTyped

    }//GEN-LAST:event_PsearchKeyTyped

    private void searchB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchB1ActionPerformed
        String query = "select * from product where ";
        if (RD.isSelected()) {
            query += "discribe ";
        }
        if (RID.isSelected()) {
            query += "id_product ";
        }
        if (RN.isSelected()) {
            query += "NUMBER ";
        }
        if (RP.isSelected()) {
            query += "price ";
        }
        if (RC.isSelected()) {
            query += "comment ";

        }
        if (RK.isSelected()) {
            query += "kind ";

        }

        query += "like '%" + searchkey.getText() + "%'";
        product p = new product();
        System.out.println(query);
        p.getCustomrow(query, TB);

    }//GEN-LAST:event_searchB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Psearch;
    private javax.swing.JRadioButton RAD;
    private javax.swing.JRadioButton RC;
    private javax.swing.JRadioButton RC1;
    private javax.swing.JRadioButton RD;
    private javax.swing.JRadioButton RID;
    private javax.swing.JRadioButton RID1;
    private javax.swing.JRadioButton RK;
    private javax.swing.JRadioButton RN;
    private javax.swing.JRadioButton RN1;
    private javax.swing.JRadioButton RP;
    private javax.swing.JTable TB;
    private javax.swing.JTable TP;
    private componentANDtools.bottonblue backB;
    private componentANDtools.bottonblue bottonblue1;
    private componentANDtools.bottonblue bottonblue2;
    private componentANDtools.bottonblue bottonblue3;
    private componentANDtools.bottonblue bottonblue4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private componentANDtools.bottonblue searchB;
    private componentANDtools.bottonblue searchB1;
    private javax.swing.JTextField searchkey;
    // End of variables declaration//GEN-END:variables
}
